apiVersion: v1
kind: ConfigMap
metadata:
  name: oficina-config
  namespace: oficina
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://oficina-db:5432/oficina"
  SPRING_DATASOURCE_USERNAME: "oficina"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_PROFILES_ACTIVE: "prod"
  MAIL_HOST: "smtp.gmail.com"
  MAIL_PORT: "587"
  APP_URL: "http://oficina-app:8080"
