apiVersion: apps/v1
kind: Deployment
metadata:
  name: oficina-db
  namespace: oficina
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oficina-db
  template:
    metadata:
      labels:
        app: oficina-db
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          env:
            - name: POSTGRES_DB
              value: oficina
            - name: POSTGRES_USER
              value: oficina
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oficina-secrets
                  key: db-password
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-data
      volumes:
        - name: db-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: oficina-db
  namespace: oficina
spec:
  selector:
    app: oficina-db
  ports:
    - port: 5432
      targetPort: 5432
