apiVersion: v1
kind: Secret
metadata:
  name: oficina-secrets
  namespace: oficina
type: Opaque
stringData:
  db-password: "oficina"
  jwt-secret: "chave-secreta-minimo-256-bits-para-o-jwt-do-sistema-oficina"
  mail-username: ""
  mail-password: ""
